### PR TITLE
add commit and buildtime vars

### PR DESCRIPTION
**Pull request by xcoulon**
fixes CRT-282

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by xcoulon** [comment]
> Looks good. But we can add at least a Unit test for it, right? e2e tests would be trickier...

yes, I can add a test to verify that these vars exist so we don't remove them by mistake, but I can't assert their values (or well, it wouldn't help much IMO)

**Comment by alexeykazakov** [comment]
> yes, I can add a test to verify that these vars exist so we don't remove them by mistake, but I can't assert their values (or well, it wouldn't help much IMO)

For values you could check the format of the build date. So, it's a date and not some random string :)

**Comment by xcoulon** [comment]
> > yes, I can add a test to verify that these vars exist so we don't remove them by mistake, but I can't assert their values (or well, it wouldn't help much IMO)
> 
> For values you could check the format of the build date. So, it's a date and not some random string :)

I don't think so: the values are set by the `-ldflags="-X ..."` arg during the `go build`, not the `go test`, so the values will still be `unknown` at this point.

**Comment by alexeykazakov** [comment]
> I don't think so: the values are set by the -ldflags="-X ..." arg during the go build, not the go test, so the values will still be unknown at this point.

Ah, right. I keep forgetting it. So, we can only test the presents of the fields itself.

**Comment by xcoulon** [comment]
> > I don't think so: the values are set by the -ldflags="-X ..." arg during the go build, not the go test, so the values will still be unknown at this point.
> 
> Ah, right. I keep forgetting it. So, we can only test the presents of the fields itself.

no worries ;) I added a (very basic) test in https://github.com/codeready-toolchain/member-operator/pull/73/commits/d57100670e2cfe61eea71361b1d32fbf856c21e3 so we can at least assert that the 2 vars exist.

**Pull request merged**
