### PR TITLE
fix: don't watch all namespaces 2.0 - use rest client this time

### PR DESCRIPTION
**Pull request by MatousJobanek**
Use REST client for listing pods from users' namespaces, so we don't have to watch all namespaces but only the operator's one \o/

### CODE REVIEW

**Review by xcoulon — APPROVED** [review]
great job, @MatousJobanek! 🙌

**Review by alexeykazakov — APPROVED** [review]
Great job indeed! :)
But I think it's time to add some e2e tests for the idler.

**Review by alexeykazakov — COMMENTED** [review]
I found a few issues in the original code and also in this PR.
Since I couldn't add e2e repo to Matous's fork I had to create a new PR based on this one: https://github.com/codeready-toolchain/member-operator/pull/204
The e2e tests are here: https://github.com/codeready-toolchain/toolchain-e2e/pull/173

**Comment by MatousJobanek** [comment]
closing in favor of https://github.com/codeready-toolchain/member-operator/pull/204

**Pull request closed without merging**
