### PR TITLE
Set CPU limit and request for Autoscaler Buffer when deploying it

### PR DESCRIPTION
**Pull request by alexeykazakov**
It takes the CPU settings from the member operator configuration.
Part of https://issues.redhat.com/browse/SANDBOX-659
Requires https://github.com/codeready-toolchain/host-operator/pull/1071

Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/1027

### CODE REVIEW

**Review by MatousJobanek — APPROVED** [review]

**Comment by MatousJobanek** [comment]
/retest
host-operator PR was merged

**Review by mfrancisc — APPROVED** [review]
Nice 👍

**Pull request merged**
