### PR TITLE
use different uuid lib

### PR DESCRIPTION
**Pull request by ranakan19**
fix wrt: https://issues.redhat.com/browse/SANDBOX-78

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Review by mfrancisc — APPROVED** [review]
Looks good! 

Just one query: are we planning to use this library in all the repos? 
I'm asking because in host-operator I've used google/uuid : https://github.com/codeready-toolchain/host-operator/blob/c899290d8eeaa9944940b1320a89710fd1b775db/test/spacerequest/spacerequest.go#L7

**Review by MatousJobanek — APPROVED** [review]
+1 to @mfrancisc. Let's align this in other repos if possible

**Comment by ranakan19** [comment]
> Just one query: are we planning to use this library in all the repos? I'm asking because in host-operator I've used google/uuid : https://github.com/codeready-toolchain/host-operator/blob/c899290d8eeaa9944940b1320a89710fd1b775db/test/spacerequest/spacerequest.go#L7

@mfrancisc host-operator does use gofrs/uuid, so will continue to use that in host as well. I made the change to use gofrs/uuid where you pointed, check it out here - https://github.com/codeready-toolchain/host-operator/pull/826

**Pull request merged**
