### PR TITLE
chore: build binary under 'build' dir

### PR DESCRIPTION
**Pull request by xcoulon**
also, use `$(OUT_DIR)` whenever possible

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by dipak-pawar** [comment]
@xcoulon, just quick question, as we are changing output directory, do we need to change this https://github.com/codeready-toolchain/member-operator/blob/master/openshift-ci/Dockerfile.deploy#L8? can you please verify we are not breaking anything

**Comment by xcoulon** [comment]
> @xcoulon, just quick question, as we are changing output directory, do we need to change this https://github.com/codeready-toolchain/member-operator/blob/master/openshift-ci/Dockerfile.deploy#L8? can you please verify we are not breaking anything

I believe this will be fine, but I believe we need to update the CI config accordingly. See https://github.com/openshift/release/pull/4272

**Comment by dipak-pawar** [comment]
> /test images

@xcoulon This will fail untill we merge openshift/release#4272

**Comment by alexeykazakov** [comment]
Just curious, any particular reason for changing it?

**Comment by xcoulon** [comment]
> Just curious, any particular reason for changing it?

we already had a `./build` dir and I thought that it would be cleaner to use something like `./build/_output` (excluded from the git repo) for the binaries, that's all

**Pull request merged**
