### PR TITLE
Remove unused code related to Che

### PR DESCRIPTION
**Pull request by filariow**
Remove Che config wrt changes in [common's #336](https://github.com/codeready-toolchain/toolchain-common/pull/336)

Signed-off-by: Francesco Ilario <filario@redhat.com>

### CODE REVIEW

**Review by baijum — APPROVED** [review]
LGTM

**Review by xcoulon — CHANGES_REQUESTED** [review]
@filariow could you also update the dependency to [toolchain-common in go.mod](https://github.com/codeready-toolchain/member-operator/blob/master/go.mod#L5) to make sure you grabbed the latest changes?

**Comment by filariow** [comment]
> @filariow could you also update the dependency to [toolchain-common in go.mod](https://github.com/codeready-toolchain/member-operator/blob/master/go.mod#L5) to make sure you grabbed the latest changes?

done

**Review by xcoulon — APPROVED** [review]

**Review by alexeykazakov — CHANGES_REQUESTED** [review]
It looks like it's already addressed in https://github.com/codeready-toolchain/member-operator/pull/496

cc: @rajivnathan

**Comment by rajivnathan** [comment]
Right, I think we removed some Che things that were still needed in https://github.com/codeready-toolchain/toolchain-common/pull/336 so I added some of them back in https://github.com/codeready-toolchain/member-operator/pull/496 as @alexeykazakov mentioned

**Pull request closed without merging**
