### PR TITLE
Ignore if rolebinding webhook fails

### PR DESCRIPTION
**Pull request by alexeykazakov**
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/511

### CODE REVIEW

**Review by rajivnathan — APPROVED** [review]

**Review by ranakan19 — APPROVED** [review]
LGTM, Thanks

**Comment by alexeykazakov** [comment]
The bundle issue again.

/retest

**Comment by alexeykazakov** [comment]
the bundle/installation problem again

/retest

**Comment by xcoulon** [comment]
Posting a link to the docs (for reference): https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy

**Pull request merged**
