### PR TITLE
fix(#343): Add permissions to scale Camel K resources

### PR DESCRIPTION
**Pull request by christophd**
Allow controller manager to scale Camel K Integration and KameletBinding custom resources on the cluster

Signed-off-by: Christoph Deppisch <cdeppisch@redhat.com>

### CODE REVIEW

**Review by xcoulon — APPROVED** [review]

**Review by alexeykazakov — APPROVED** [review]

**Comment by alexeykazakov** [comment]
/re-test

Infra issue

**Comment by alexeykazakov** [comment]
/retest

Infra issue

**Comment by alexeykazakov** [comment]
/retest

Infra issue

**Pull request merged**
