### PR TITLE
fix: don't intercept updates in users pods webhook

### PR DESCRIPTION
**Pull request by MatousJobanek**
https://github.com/kubernetes/kubernetes/issues/109164#issuecomment-1085055715
we should not intercept updates because the priorityClassName nor priority cannot be changed in update requests.

paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/527

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Comment by alexeykazakov** [comment]
/retest

infra

**Review by rajivnathan — APPROVED** [review]

**Review by xcoulon — APPROVED** [review]

**Comment by MatousJobanek** [comment]
/retest 
infra

**Pull request merged**
