### PR TITLE
Remove NSLimit and NSTemplateSet

### PR DESCRIPTION
**Pull request by rajivnathan**
Related Issue: https://issues.redhat.com/browse/CRT-1326

Removes NSLimit and NSTemplateSet from UserAccount

Related PRs:
- https://github.com/codeready-toolchain/api/pull/301
- https://github.com/codeready-toolchain/toolchain-e2e/pull/536

### CODE REVIEW

**Review by MatousJobanek — APPROVED** [review]
The UserAccount controller still watches the NSTemplatset CRD - you can drop that.
Otherwise, it looks good

**Comment by rajivnathan** [comment]
Thanks for the review Matous, good catch about the UserAccount not having to watch NSTemplateSet now. Removed in https://github.com/codeready-toolchain/member-operator/pull/355/commits/4aac78c79639928d4b24ca28d6e89ad63fef6da3

**Comment by rajivnathan** [comment]
@MatousJobanek unfortunately I had to bring the NSTemplateSet watch back because we rely on it for some appstudio-specific cases handled in the UserAccount controller. See https://github.com/codeready-toolchain/member-operator/pull/355/commits/46aaa44333048df4b7f1c2a0cb385345b1ae427a for details

**Pull request merged**
