### PR TITLE
CRT-953 support multiple roles for nodes

### PR DESCRIPTION
**Pull request by sbryzak**
Fixes https://issues.redhat.com/browse/CRT-953

Adds support for multi-role nodes.

### CODE REVIEW

**Comment by xcoulon** [comment]
@sbryzak could you add some tests to verify these changes?

**Comment by sbryzak** [comment]
@xcoulon we actually have e2e tests for this already which are broken when running in CRC, this fix allows the tests to pass again at least in CRC so if we get a pass in CI also then we should be well covered.

**Comment by MatousJobanek** [comment]
Looks good :+1: 
I agree that there is no need for e2e tests, but could you please add a unit test for the case when one node is used for both roles?

**Comment by xcoulon** [comment]
> Looks good 👍
> I agree that there is no need for e2e tests, but could you please add a unit test for the case when one node is used for both roles?

yes, at least a unit test would be nice, since if I understand correctly, our current e2e tests on OpenShift CI do pass with our without this fix.

**Comment by alexeykazakov** [comment]
Agree that we need to at least some tests. The CRC test coverage is not enough because our PR checks do not run against CRC. We can't rely on manual testing.
Let's add some simple unit tests.

**Comment by sbryzak** [comment]
I've added support in the test for specifying multiple roles for a node, and added a unit test that tests a multi-role node.

**Review by alexeykazakov — APPROVED** [review]
Thanks for the test Shane.

**Review by MatousJobanek — APPROVED** [review]
Cool :+1: :1st_place_medal:

**Pull request merged**
